export const hog="HOGASH STUDIOS"
export const hog2="We're a full-service digital agency that believes being a Favorite brand is more valuable than just being a Famous one. We craft beautifully useful, connected ecosystems that grow businesses and build enduring relationships between brands and humans."
export const footerLogo="/images/Header-logo.png"
export const CompanyName="COMPANY"
export const CompanyName2="Our Blog"
export const CompanyName3="Instagram"
export const CompanyName4="Snapchat"
export const CompanyName5="Facebook"
export const CompanyName6="Twitter"

export const member="MEMBER"
export const member1="Home"
export const member2="About"
export const member3="Pricing"
export const member4="Blog"
export const member5="Service"
export const member6="Shop"

export const follow="FOLLOW"
export const follow1="Account"
export const follow2="Billing"
export const follow3="Membership"
export const follow4="Receipt"
export const follow5="Invoice"